// Code generated by protoc-gen-go. DO NOT EDIT.
// source: talks.proto

package talks

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Talk struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Repository           string   `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	Date                 int64    `protobuf:"varint,5,opt,name=date,proto3" json:"date,omitempty"`
	Tags                 string   `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	UserUserId           string   `protobuf:"bytes,7,opt,name=user_user_id,json=userUserId,proto3" json:"user_user_id,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Talk) Reset()         { *m = Talk{} }
func (m *Talk) String() string { return proto.CompactTextString(m) }
func (*Talk) ProtoMessage()    {}
func (*Talk) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{0}
}

func (m *Talk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Talk.Unmarshal(m, b)
}
func (m *Talk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Talk.Marshal(b, m, deterministic)
}
func (m *Talk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Talk.Merge(m, src)
}
func (m *Talk) XXX_Size() int {
	return xxx_messageInfo_Talk.Size(m)
}
func (m *Talk) XXX_DiscardUnknown() {
	xxx_messageInfo_Talk.DiscardUnknown(m)
}

var xxx_messageInfo_Talk proto.InternalMessageInfo

func (m *Talk) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Talk) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Talk) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Talk) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Talk) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Talk) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Talk) GetUserUserId() string {
	if m != nil {
		return m.UserUserId
	}
	return ""
}

func (m *Talk) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Talk) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GetRequest struct {
	TalkId               string   `protobuf:"bytes,1,opt,name=talk_id,json=talkId,proto3" json:"talk_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetTalkId() string {
	if m != nil {
		return m.TalkId
	}
	return ""
}

type GetResponse struct {
	Talk                 *Talk    `protobuf:"bytes,1,opt,name=talk,proto3" json:"talk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetTalk() *Talk {
	if m != nil {
		return m.Talk
	}
	return nil
}

type SelectRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectRequest) Reset()         { *m = SelectRequest{} }
func (m *SelectRequest) String() string { return proto.CompactTextString(m) }
func (*SelectRequest) ProtoMessage()    {}
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{3}
}

func (m *SelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectRequest.Unmarshal(m, b)
}
func (m *SelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectRequest.Marshal(b, m, deterministic)
}
func (m *SelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectRequest.Merge(m, src)
}
func (m *SelectRequest) XXX_Size() int {
	return xxx_messageInfo_SelectRequest.Size(m)
}
func (m *SelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectRequest proto.InternalMessageInfo

type SelectResponse struct {
	Talk                 []*Talk  `protobuf:"bytes,1,rep,name=talk,proto3" json:"talk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectResponse) Reset()         { *m = SelectResponse{} }
func (m *SelectResponse) String() string { return proto.CompactTextString(m) }
func (*SelectResponse) ProtoMessage()    {}
func (*SelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{4}
}

func (m *SelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectResponse.Unmarshal(m, b)
}
func (m *SelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectResponse.Marshal(b, m, deterministic)
}
func (m *SelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectResponse.Merge(m, src)
}
func (m *SelectResponse) XXX_Size() int {
	return xxx_messageInfo_SelectResponse.Size(m)
}
func (m *SelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelectResponse proto.InternalMessageInfo

func (m *SelectResponse) GetTalk() []*Talk {
	if m != nil {
		return m.Talk
	}
	return nil
}

type CreateRequest struct {
	Talk                 *Talk    `protobuf:"bytes,1,opt,name=talk,proto3" json:"talk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{5}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTalk() *Talk {
	if m != nil {
		return m.Talk
	}
	return nil
}

type CreateResponse struct {
	Talk                 *Talk    `protobuf:"bytes,1,opt,name=talk,proto3" json:"talk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{6}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetTalk() *Talk {
	if m != nil {
		return m.Talk
	}
	return nil
}

type UpdateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

type UpdateResponse struct {
	Talk                 *Talk    `protobuf:"bytes,1,opt,name=talk,proto3" json:"talk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{8}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetTalk() *Talk {
	if m != nil {
		return m.Talk
	}
	return nil
}

type DeleteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

type DeleteResponse struct {
	Talk                 *Talk    `protobuf:"bytes,1,opt,name=talk,proto3" json:"talk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6541a5a4ec1fb622, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetTalk() *Talk {
	if m != nil {
		return m.Talk
	}
	return nil
}

func init() {
	proto.RegisterType((*Talk)(nil), "talks.Talk")
	proto.RegisterType((*GetRequest)(nil), "talks.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "talks.GetResponse")
	proto.RegisterType((*SelectRequest)(nil), "talks.SelectRequest")
	proto.RegisterType((*SelectResponse)(nil), "talks.SelectResponse")
	proto.RegisterType((*CreateRequest)(nil), "talks.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "talks.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "talks.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "talks.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "talks.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "talks.DeleteResponse")
}

func init() { proto.RegisterFile("talks.proto", fileDescriptor_6541a5a4ec1fb622) }

var fileDescriptor_6541a5a4ec1fb622 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x8b, 0xdb, 0x30,
	0x10, 0x85, 0x63, 0x3b, 0x71, 0x9a, 0x71, 0x93, 0xd2, 0x21, 0xa5, 0x22, 0xd0, 0xd6, 0x18, 0x0a,
	0x39, 0x99, 0x26, 0x3d, 0xf4, 0x1c, 0x5a, 0x08, 0xb9, 0xba, 0xcd, 0x39, 0xb8, 0xd1, 0x10, 0x44,
	0x4c, 0xec, 0x5a, 0xca, 0xa1, 0x3f, 0xa6, 0x7f, 0xb3, 0xe7, 0x45, 0x92, 0xed, 0xb5, 0x76, 0x17,
	0x76, 0x73, 0x31, 0x9a, 0x37, 0xf3, 0x9e, 0xc7, 0x9f, 0x11, 0x44, 0x2a, 0x2f, 0xce, 0x32, 0xad,
	0xea, 0x52, 0x95, 0x38, 0x32, 0x45, 0xf2, 0xdf, 0x83, 0xe1, 0xaf, 0xbc, 0x38, 0xe3, 0x0c, 0x7c,
	0xc1, 0x99, 0x17, 0x7b, 0xcb, 0x49, 0xe6, 0x0b, 0x8e, 0x73, 0x18, 0x29, 0xa1, 0x0a, 0x62, 0xbe,
	0x91, 0x6c, 0x81, 0x31, 0x44, 0x9c, 0xe4, 0xb1, 0x16, 0x95, 0x12, 0xe5, 0x85, 0x05, 0xa6, 0xd7,
	0x97, 0xf0, 0x23, 0x40, 0x4d, 0x55, 0x29, 0x85, 0x2a, 0xeb, 0xbf, 0x6c, 0x68, 0x06, 0x7a, 0x0a,
	0x22, 0x0c, 0x79, 0xae, 0x88, 0x8d, 0x62, 0x6f, 0x19, 0x64, 0xe6, 0xac, 0x35, 0x95, 0x9f, 0x24,
	0x0b, 0xcd, 0xb4, 0x39, 0x63, 0x0c, 0xaf, 0xaf, 0x92, 0xea, 0x83, 0x79, 0x08, 0xce, 0xc6, 0x36,
	0x49, 0x97, 0x7b, 0x49, 0xf5, 0x8e, 0xe3, 0x07, 0x80, 0x63, 0x4d, 0xb9, 0x22, 0x7e, 0xc8, 0x15,
	0x7b, 0x65, 0xf2, 0x26, 0x8d, 0xb2, 0x51, 0xba, 0x7d, 0xad, 0x78, 0xdb, 0x9e, 0xd8, 0x76, 0xa3,
	0x6c, 0x54, 0xf2, 0x19, 0x60, 0x4b, 0x2a, 0xa3, 0x3f, 0x57, 0x92, 0x0a, 0xdf, 0xc3, 0x58, 0xf3,
	0x38, 0x74, 0x08, 0x42, 0x5d, 0xee, 0x78, 0x92, 0x42, 0x64, 0xc6, 0x64, 0x55, 0x5e, 0x24, 0xe1,
	0x27, 0xbd, 0x69, 0x71, 0x36, 0x43, 0xd1, 0x3a, 0x4a, 0x2d, 0x51, 0x0d, 0x30, 0x33, 0x8d, 0xe4,
	0x0d, 0x4c, 0x7f, 0x52, 0x41, 0xc7, 0x36, 0x39, 0x59, 0xc1, 0xac, 0x15, 0x1e, 0x65, 0x04, 0x4f,
	0x67, 0x7c, 0x81, 0xe9, 0x77, 0xf3, 0x19, 0xed, 0x76, 0xcf, 0xbe, 0x75, 0x05, 0xb3, 0xd6, 0x71,
	0xc3, 0xa2, 0x7b, 0x03, 0xa3, 0xb7, 0x68, 0x2b, 0xdc, 0x90, 0xf1, 0x83, 0x0a, 0x72, 0x32, 0x5a,
	0xe1, 0x85, 0x19, 0xeb, 0x7f, 0x3e, 0x8c, 0x75, 0x29, 0x2e, 0x27, 0x4c, 0x21, 0xd8, 0x92, 0xc2,
	0xb7, 0xcd, 0xd4, 0xfd, 0xff, 0x59, 0x60, 0x5f, 0xb2, 0xd1, 0xc9, 0x00, 0xbf, 0x41, 0x68, 0xd9,
	0xe2, 0xbc, 0xe9, 0x3b, 0xec, 0x17, 0xef, 0x1e, 0xa8, 0x7d, 0xa3, 0xe5, 0xd5, 0x19, 0x1d, 0xe0,
	0x9d, 0xd1, 0x85, 0x6a, 0x8d, 0x16, 0x52, 0x67, 0x74, 0x20, 0x76, 0x46, 0x97, 0xa4, 0x35, 0x5a,
	0x32, 0x9d, 0xd1, 0x21, 0xd7, 0x19, 0x5d, 0x7c, 0xc9, 0xe0, 0x77, 0x68, 0xae, 0xeb, 0xd7, 0xbb,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xa1, 0x91, 0xf7, 0xbd, 0x03, 0x00, 0x00,
}
